codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        paths:
          - "src/"
          
    patch:
      default:
        target: 80%
        threshold: 5%
        
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "tests/"
  - "docs/"
  - "notebooks/"
  - "**/__init__.py"
  - "**/conftest.py"
  - "setup.py"
  
flags:
  unittests:
    paths:
      - src/
    carryforward: false
    
  integration:
    paths:
      - src/
    carryforward: false 