version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      - qdrant:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
      
  redis:
    image: valkey/valkey:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command: valkey-server --appendonly yes
    
# Define volumes
volumes:
  qdrant:
  redis: 